# Site settings
title: over-engineering
# email: your-email@domain.com
description: "The blog/personal homepage of David Jackson. He writes code."
baseurl: ""
url: "http://forspareparts.github.io"
twitter_username: ForSpareParts
github_username:  ForSpareParts

# Build settings
markdown: kramdown
permalink: pretty


excerpt_separator: "<!-- more -->"

plugins:
  - jekyll-gist
